spring:
  datasource:
    url: jdbc:h2:mem:library1718
  jpa:
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  sql:
    init:
      mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true

logging:
  file:
    path: ./src/main/resources

resilience4j.circuitbreaker:
  instances:
    books:
      timeoutDuration: 1s
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 1s
      cancelRunningFuture: true