spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: larionova
  datasource:
    url: jdbc:h2:mem:library14
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  #        enable_lazy_load_no_trans: true

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: spring14.db
  mongo-db:
    write-concern:
      journal: false
    read-concern: local